# Generated by Django 5.2.7 on 2025-12-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.PositiveIntegerField()),
                ('options', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Theme',
                'verbose_name_plural': 'Shop Themes',
                'db_table': 'shops_theme',
            },
        ),
    ]
