# Generated by Django 5.2.7 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shoptheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptheme',
            name='template_id',
            field=models.CharField(max_length=100),
        ),
    ]
