# Generated by Django 5.2.7 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shoptheme_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20),
        ),
    ]
